<!DOCTYPE html>
<html lang="cs-cz">
    <head>
<!--        <base href="http://--><?php //= $domain ?><!--" />-->
        <meta charset="UTF-8" />
<!--        <title>--><?php //= $this->title ?><!--</title>-->
<!--        <meta name="description" content="--><?php //= $description ?><!--" />-->
<!--        <meta name="keywords" content="--><?php //= $keywords ?><!--" />-->
        <link rel="stylesheet" href="css/style.css" type="text/css"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>

    <body>
        <header>
            <nav>
                <ul>
					<?php foreach($pages as $page): ?>
					    <?php if($page['page_id'] <= 4): ?>
                        <li>
							<a href=<?= $page['url']; ?>><?= $page['title']; ?></a>
                        </li>
                        <?php endif; ?>
					<?php endforeach; ?>
                </ul>
            </nav>
        </header>
        <article>
<!--            <h1>--><?php //= $this->title ?><!--</h1>-->
            <?php $this->controller->renderView(); ?>
        </article>
        <footer>
            Matěj Musil Copyright <?= new DateTime()->format('Y') ?>
        </footer>
    </body>
</html>