<!DOCTYPE html>
<html lang="cs-cz">
    <head>
<!--        <base href="http://--><?php //= $domain ?><!--" />-->
        <meta charset="UTF-8" />
<!--        <title>--><?php //= $this->title ?><!--</title>-->
<!--        <meta name="description" content="--><?php //= $description ?><!--" />-->
<!--        <meta name="keywords" content="--><?php //= $keywords ?><!--" />-->
        <link rel="stylesheet" href="css/style.css" type="text/css"/>
        <link rel="stylesheet" href="css/bootstrap/css/bootstrap.min.css" type="text/css"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>

    <body class="container-sm">
        <header>
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="/">Navbar</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div class="navbar-nav">
							<?php foreach($pages as $page): ?>
							    <?php if($page['page_id'] <= 4): ?>
                                    <a class="nav-link" href=<?= $page['url']; ?>><?= $page['title']; ?></a>
								<?php endif; ?>
							<?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <article>
<!--            <h1>--><?php //= $this->title ?><!--</h1>-->
            <?php $this->controller->renderView(); ?>
        </article>
        <footer>
            Matěj Musil Copyright <?= new DateTime()->format('Y') ?>
        </footer>
        <script type="text/javascript" src="css/bootstrap/js/bootstrap.min.js"></script>
    </body>
</html>