<!DOCTYPE html>
<html lang="cs-cz">
	<head>
		<base href="http://<?= $domain ?>" />
		<meta charset="UTF-8" />
		<title><?= $title ?></title>
		<meta name="description" content="<?= $description ?>" />
		<meta name="keywords" content="<?= $keywords ?>" />
		<link rel="stylesheet" href="css/style.css" type="text/css"/>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	</head>

	<body>
		<article>
			<?php $this->controller->renderView(); ?>
		</article>
	</body>
</html>