services:
  php:
    platform: "linux/amd64"
    container_name: todo_php
    image: mckillem/todo_php
    build:
      context: build/php
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    volumes:
      - ../:/var/www/html
    ports:
      - "8088:80"
    environment:
      - NETTE_DEBUG=1
#      - COMPOSER_AUTH=${COMPOSER_AUTH}
    links:
      - database

  database:
    container_name: todo_php_db
    image: mckillem/todo_php_db
    build:
      context: build/database
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: todo_php_db
    volumes:
      - ./build/database/01_create.sql:/docker-entrypoint-initdb.d/01_create.sql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8089:80"
    environment:
      - PMA_HOST=database
      - PMA_USER=test
      - PMA_PASSWORD=test