<form method="post">
    <input type="hidden" name="contact_id" value="<?php if (isset($this->contact['contact_id'])) echo($this->contact['contact_id']) ?>" />
    <label>
        Váš email<br />
        <input type="email" name="email" required="required" value="<?php if (isset($this->contact['email'])) echo($this->contact['email']) ?>" />
    </label><br />
    <label>
        Zpráva<br />
        <input type="text" name="text" required="required" value="<?php if (isset($this->contact['text'])) echo($this->contact['text']) ?>" />
    </label><br />
    captcha
    <input type="submit" value="Odeslat" />
</form>