<?= $message ?? '' ?>
<form method="post">
    <label>
        Váš email<br />
        <input type="email" name="email" required="required" value="<?= htmlspecialchars($email) ?>" />
    </label><br />
    <label>
        Zpráva<br />
        <textarea name="text" required="required"><?= htmlspecialchars($text) ?></textarea>
    </label><br />
    <label>
        Jaký je dnes rok?<br />
        <input type="text" name="year" required="required" />
    </label><br />
    <input type="submit" value="Odeslat" />
</form>