<!DOCTYPE html>
<html lang="cs-cz">
    <head>
<!--        <base href="http://--><?php //= $domain ?><!--" />-->
        <meta charset="UTF-8" />
<!--        <title>--><?php //= $title ?><!--</title>-->
<!--        <meta name="description" content="--><?php //= $description ?><!--" />-->
<!--        <meta name="keywords" content="--><?php //= $keywords ?><!--" />-->
        <link rel="stylesheet" href="css/style.css" type="text/css"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>

    <body>
        <article>
            <section>
                <h1>Úkolovník</h1>
                <a href="?action=edit">Přidat úkol</a>
                <ul>
                    <?php foreach($this->getAllTodos() as $todo): ?>
                        <li><?= $todo['text']; ?></li>
                        <a href="?id=<?=$todo['todo_id']?>&action=delete" class="trash"><i class="fas fa-trash fa-xs">Smazat</i></a>
                        <a href="?id=<?=$todo['todo_id']?>&action=edit" class="trash"><i class="fas fa-trash fa-xs">Upravit</i></a>

                    <?php endforeach; ?>
                </ul>
            </section>
        </article>
    </body>
</html>