<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="http://<?= $domain ?>" />
        <meta charset="UTF-8" />
        <title><?= $title ?></title>
        <meta name="description" content="<?= $description ?>" />
        <meta name="keywords" content="<?= $keywords ?>" />
        <link rel="stylesheet" href="css/style.css" type="text/css"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>

    <body>
        <article>
            <section>
                <h1>Úkolovník</h1>
                <table>
                    <?php foreach($this->getAllTodos() as $todo): ?>
                        <?php foreach($todo as $t): ?>
                            <tr>
                                <td><?= $t; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </table>

                <form method="post">
<!--                    <input type="hidden" name="todo_id" value="--><?php //= $todo['todo_id'] ?><!--" />-->
                    <input type="hidden" name="todo_id" />
                    <label>
                        Nový úkol<br />
<!--                        <input type="text" name="text" required="required" value="--><?php //= $todo['text'] ?><!--" />-->
                        <input type="text" name="text" required="required" />
                    </label><br />
                    <input type="submit" value="Přidat" />
                </form>
            </section>
        </article>
    </body>
</html>