<!DOCTYPE html>
<html lang="cs-cz">
    <head>
<!--        <base href="http://--><?php //= $domain ?><!--" />-->
        <meta charset="UTF-8" />
<!--        <title>--><?php //= $title ?><!--</title>-->
<!--        <meta name="description" content="--><?php //= $description ?><!--" />-->
<!--        <meta name="keywords" content="--><?php //= $keywords ?><!--" />-->
        <link rel="stylesheet" href="css/style.css" type="text/css"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>

    <body>
        <article>
            <section>
                <h1>Úkolovník</h1>
                <?php var_dump($this->getAllTodos()); ?>
                <ul>
                    <?php foreach($this->getAllTodos() as $todo): ?>
                        <li><?= $todo['text']; ?></li>
<!--                        <li>--><?php //= $todo['text']; ?><!--<button onclick="--><?php //= $this->deleteTodo($todo['todo_id']) ?><!--">Smazat</button></li>-->

<!--                        <a href="delete.php?id=--><?php //=$todo['todo_id']?><!--" class="trash"><i class="fas fa-trash fa-xs"></i></a>-->
                        <a href="delete.php?id=<?=$todo['todo_id']?>" class="trash"><i class="fas fa-trash fa-xs">Smazat</i></a>

                    <?php endforeach; ?>
                </ul>
                <form method="post">
                    <input type="hidden" name="todo_id" value="<?php if (isset($_POST['text'])) echo(htmlspecialchars($_POST['text'])); ?>" />
<!--                    <input type="hidden" name="todo_id" value="--><?php //= $todo['todo_id'] ?><!--" />-->
<!--                    <input type="hidden" name="todo_id" />-->
                    <label>
                        Nový úkol<br />
                        <input type="text" name="text" required="required" value="<?php if (isset($_POST['text'])) echo(htmlspecialchars($_POST['text'])); ?>" />

<!--                        <input type="text" name="text" required="required" value="--><?php //= $todo['text'] ?><!--" />-->
<!--                        <input type="text" name="text" required="required" />-->
                    </label><br />
                    <input type="submit" value="Přidat" />
                </form>
            </section>
        </article>
    </body>
</html>